Implementation of collapsible sections
zeel01/MonsterBlocks pull request #169
Opened 2022-03-09 02:39 UTC by jeremyregnerus

Resolves #163 Make each section (feats, actions, bonus, legendary, etc) an accordion that can be collapsed.

- This implementation adds a show-collapsible option to enable or disable collapsible sections of the sheet.
   - I could not find a way to incorporate an `enabled` setting into the `collapsible` object which controls the state of the other sections, and have this option to enable / disable this from the module settings page.
   - This option can be controlled from the module settings or from the actor sheet
- Once enabled, the Features section will show a header (more about this below).
- Each header has a collapsible icon that appears when hovering over the header
   - This could be set to appear when hovering over the entire section, however I felt this could be distracting
- The collapsed state of each section is preserved when the actor sheet is closed and re-opened and across sessions
- If you disable the show-collapsible option, all of the sections _expand_
- This implementation utilizes a new header partial, which includes options for showing resources beyond legendary resources
   - This new header partial also contains partials which contain the section content, this is used to control the visibility of this section
   - This is done using a show / no show condition. I also considered adding the `hidden` class to the wrapper instead, but I'm not sure of the pros and cons of using either method
- Moved loot to the end of the character sheet. Currently it appears between legendary and lair actions
- Added google translated localization strings to localization files

2022-03-09 17:53 UTC, zeel01 requested changes
Alright, I made a lot of comments. Some of these things might be things I should work on, but I mentioned anyway for completions sake.

One thing I want to consider, and unfortunately it would be a lot of changes... `collapsible` is not an easy word to not typo, and every time I look at it I don't believe it's spelled that way even though Google tells me it.

I'm not sure if there is a great alternative. I usually refer to this sort of thing as an "accordion" but that's also kind of a tricky word to get right all the time. So idk if it makes sense to change this, or if there is a better term to use that will be less trouble.

Also, the changes in `main.hbs` are bit hard to follow in the way Github presents them, so I may have missed some things in that area,

2022-03-09 17:53 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> +			this.flagManager.flags.collapsible = collapsible;
`this.flags` is an alias to `this.flagManager.flags` that for some reason I haven't refactored all the code to use. It's defined up on line `49`.

2022-03-09 17:53 UTC, zeel01 commented on templates/dnd5e/switches.hbs
> +					on="MOBLOKS5E.show-collaspsible.disable"
Typo here, "coll**asp**sible" on both strings, so it ends up not localizing.

2022-03-10 18:29 UTC, jeremyregnerus commented on monsterblock.css
> +.monsterblock .collapsible {
Do you mean, you want two classes on the tag element, 1 for the display properties, and another for the command itself? Something like
```html
<a class="collapsible collapsible-button">
```

2022-03-10 20:57 UTC, zeel01 commented on monsterblock.css
> +.monsterblock .collapsible {
No, I would just make it `<a class="collapsible-button">`. The idea being that the `<a>` tag is just a button, it's not itself collapsible. The `<section>` that gets hidden is "collapsible" but the anchor is just a button. So the class `.collapsible` is slightly confusing.

2022-03-10 21:37 UTC, jeremyregnerus commented
Commit https://github.com/zeel01/MonsterBlocks/pull/169/commits/ff3f548bba5471051b43b50988b5828241f6b2fe
Right now, I have everything resolved with the exception of the float: right suggestion. I'm struggling to get a `flex` to work while keeping the Title left justified and the resources and collapsible switch right justified. Everything I do either adds a new line, or doesn't justify the last two.
Also, I did notice that `header-resource` is currently using `float: right` as well (which I've tried to remove as part of doing this). Possibly you could provide some insight on the correct way to do this.

2022-03-10 22:01 UTC, zeel01 commented
> Commit [ff3f548](https://github.com/zeel01/MonsterBlocks/commit/ff3f548bba5471051b43b50988b5828241f6b2fe) Right now, I have everything resolved with the exception of the float: right suggestion. I'm struggling to get a `flex` to work while keeping the Title left justified and the resources and collapsible switch right justified. Everything I do either adds a new line, or doesn't justify the last two. Also, I did notice that `header-resource` is currently using `float: right` as well (which I've tried to remove as part of doing this). Possibly you could provide some insight on the correct way to do this.

That's fine, I can fix that.

2022-03-10 22:29 UTC, jeremyregnerus commented
This was my attempt at changing the floats to flex
https://github.com/zeel01/MonsterBlocks/pull/169/commits/4376c78a224272c10a29b23daefd66c63cf6bfa0

2022-03-11 02:57 UTC, zeel01 requested changes

2022-03-11 02:57 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> +			data.info.hasLoot);
Nitpick: I prefer to put the closing `);` on the next line.

2022-03-11 02:57 UTC, zeel01 commented on templates/dnd5e/main.hbs
> +		{{#> "modules/monsterblock/templates/dnd5e/collapsibleSection.hbs" title="DND5E.Features" hide-title=true section="feats" flag=flags.collapsed.feats }}
We could maybe use the [`lookup` helper](https://handlebarsjs.com/guide/builtin-helpers.html#lookup) to find the flag in `flags.collapsed` using the `section` parameter? In the partial it might look like:
```handlebars
{{#unless (and flags.show-collapsible (lookup flags.collapsed section))}}
    {{> @partial-block}}
{{/unless}}
```
Then we could drop the `flag` parameter.

2022-03-11 13:35 UTC, jeremyregnerus reviewed
Updates made based on latest comments. Was trying to use lookup to simplify adding the attributes for value / max to the sectionHeader

2022-03-11 15:25 UTC, zeel01 approved these changes
Awesome. Nice work!

2022-03-11 15:25 UTC, merged