Quick toggle to sheet image
zeel01/MonsterBlocks pull request #185
Opened 2022-03-20 12:54 UTC by jeremyregnerus

Adds a modifier click to the sheet image to change the use-token-image toggle. This makes is really fast to change between images for sharing with the players.

https://user-images.githubusercontent.com/7407481/159163260-398af034-8640-49e8-b395-939e1cd7e59e.mp4

2022-03-21 05:12 UTC, zeel01 requested changes
Seems like a reasonable idea. I'll merge in this and the others after I get all the spellcasting stuff done, then I can do all the merging and any conflict resolution in one go.

2022-03-21 05:12 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> +			} else {
I prefer to use the "early return pattern" for this sort of condition. Rather than an `if/else`, you just to do the `if` and add a `return` inside of it.

2022-03-21 05:12 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> +			if (event.altKey || event.ctrlKey || event.shiftKey) {
*Any* of the three modifiers? Seems a little odd.

What if instead, one modifier is used to switch images, and maybe another one shows the popup and also instantly shares it?

2022-03-21 05:12 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> +				this.flagManager.flags["use-token-image"] = !this.flagManager.flags["use-token-image"];
Feel like maybe I should add a "toggle" method of some sort to the flag manager. Would make lines like this more readable if it were just `this.flagManager.toggle("use-token-image")` or something like that. Most of the flags are booleans, so this is pretty common in the code.

2022-03-21 14:31 UTC, jeremyregnerus commented on scripts/dnd5e/MonsterBlock5e.js
> +			} else {
hehehe, I do the same thing in C#. I didn't realize, or look how you were doing that here. I'll make that change.

2022-03-23 03:12 UTC, jeremyregnerus commented on templates/dnd5e/parts/header/identity.hbs
> +			title="{{actor.name}}{{#if flags.editing}} - {{localize "MOBLOKS5E.EditHint"}}{{/if}}{{localize "MOBLOKS5E.ProfileImageHint"}}">
I am struggling to get consistent line breaks and spaces for the tooltip on this. Still need to resolve this.

2022-03-25 19:00 UTC, jeremyregnerus commented
Converted draft, waiting for #182 Spellcasting Refactor to rebase.

2022-03-26 13:06 UTC, jeremyregnerus commented
Updated tooltip for the profile image is as follows with latest commit
![image](https://user-images.githubusercontent.com/7407481/160240809-df3c701e-791e-44e9-86ac-5d04abe7049c.png)

2023-01-13 14:47 UTC, closed without merging