Foundry v10 Support
zeel01/MonsterBlocks pull request #199
Opened 2022-09-27 17:40 UTC by Rencos1

2022-09-27 19:25 UTC, zeel01 requested changes
I haven't had a chance to pull this and test it yet, but I've done a quick code review.

My plan is/was to try to release a patch `v3.3.1` which would ideally be v9/v10 cross compatible, with bare-minimum changes to make it work. I'm in the middle of a bigger update, and don't want to go through and patch all the deprecations and such until after I complete that work. This PR, assuming it works, should fit the bill for what I wanted to release - as long as it can run on both versions.

If it's not possible to get a release out that's cross-compatible... well then that's just unfortunate. But if it is possible, that what I want to do.

What I might do, is just tag a release on this branch instead of fully merging it at this time. When I finish my big update I'll see if it merges cleanly or not.

There are a handful of things I noted that will need changed. I'll try to actually *test* this later tonight or tomorrow, and if all is well I can create a release with it.

2022-09-27 19:25 UTC, zeel01 commented on module.json
> +	"version": "3.4.0",
I'm planning to release this as 3.3.1, as this will only be a patch to make it work in v10. I'm working on a pretty big update, which will be 3.4.0.

2022-09-27 19:25 UTC, zeel01 commented on module.json
> +	"compatibleCoreVersion": "10",
Does this PR really break compatibility with v9? I was hoping to be able to make a release that was cross compatible.

If this really does break compatibility with v9, and we can't avoid doing so, we will also want to fully migrate the manifest: https://foundryvtt.com/article/manifest-migration-guide/

2022-09-27 19:25 UTC, zeel01 commented on module.json
>  	"minimumSystemVersion": "1.5.0",
Does the min system version not need to change?

2022-09-27 19:25 UTC, zeel01 commented on scripts/dnd5e/AttackPreper.js
> +		var simplifyRollFormula = dice?.simplifyRollFormula;
Do not use `var`. Use only `let` or `const`. In this case, the appropriate choice is `const`.

Since this function isn't being used multiple times here though, I would probably just change the last three lines to:
```js
return game[game.system.id].dice?.simplifyRollFormula(roll.formula);
```
Though... is there *actually* a chance that `dice` doesn't exist? If so, we might need to add something to handle that case and take an alternate path. If it can't really fail to exist, then we should remove the `?.` so that we don't eat an error if something really weird happens.

2022-09-27 19:25 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> + .ActorSheet5eNPC {
I wouldn't split this into two lines, it puts the opening `{` brace in a weird spot and makes the first line seem incomplete.

2022-09-27 19:25 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> +		const data = await super.getData();
Did the system `getData` change to async? This could potentially have side effects.

2022-09-27 19:25 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> +		data.data.attributes.hp.average = this.constructor.averageRoll(data.data.attributes.hp.formula, data.rollData);
What changed here?

2022-09-28 19:52 UTC, Rencos1 commented on module.json
> +	"compatibleCoreVersion": "10",
It's not working on v9. But maybe there is way to make it work on both v9 and v10.

2022-09-28 19:56 UTC, Rencos1 commented on module.json
>  	"minimumSystemVersion": "1.5.0",
Yes if it support a lower version.

2022-09-28 20:00 UTC, Rencos1 commented on scripts/dnd5e/MonsterBlock5e.js
> + .ActorSheet5eNPC {
I just did a copy paste from another module, you can put it on the same line.

2022-09-28 20:01 UTC, Rencos1 commented on scripts/dnd5e/MonsterBlock5e.js
> +		const data = await super.getData();
Yes super.getData() is async. I tried without it and the data is empty.

2022-09-28 22:07 UTC, friction1 commented
I'm not sure how best to help but just reporting a few errors with the latest PR. 
<img width="973" alt="Screen Shot 2022-09-28 at 6 02 49 PM" src="https://user-images.githubusercontent.com/11384891/192897049-23833e29-d72b-426d-ac5a-a4a84ec09ef9.png">

**When opening my world:**
Uncaught (in promise) Error: ENOENT: no such file or directory, open '/Users/friction1/Library/Application Support/FoundryVTT/Data/modules/monsterblock/templates/dnd5e/collapsibleSection.hbs'
[Detected 1 package: monsterblock]
    at i.<anonymous> (foundry.js:6841)
    at i.value (socket.io.min.js:6)
    at i.value (socket.io.min.js:6)
    at s.x.emit (socket.io.min.js:6)
    at s.value (socket.io.min.js:6)
    at a.x.emit (socket.io.min.js:6)
    at a.value (socket.io.min.js:6)
    at s.value (socket.io.min.js:6)
    at a.x.emit (socket.io.min.js:6)
    at a.value (socket.io.min.js:6)
    at i.x.emit (socket.io.min.js:6)
    at i.value (socket.io.min.js:6)
    at i.value (socket.io.min.js:6)
    at WebSocket.ws.onmessage (socket.io.min.js:6)

**When opening a dnd5e mummy:**
commons.js:1696 Error: You are accessing the "data" attribute within the rendering context provided by the ActorSheet5e 
        class. This attribute has been deprecated in favor of "system" and will be removed in a future release
Deprecated since Version DnD5e 2.0
Backwards-compatible support will be removed in Version DnD5e 2.2
    at Object.logCompatibilityWarning (commons.js:1685)
    at Object.get (base-sheet.mjs:116)
    at lookupProperty (handlebars.min.js:27)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29), <anonymous>:16:322)
    at c (handlebars.min.js:27)
    at d (handlebars.min.js:27)
    at e (handlebars.min.js:28)
    at Object.h (handlebars.min.js:27)
    at Object.c [as invokePartial] (handlebars.min.js:27)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29), <anonymous>:21:28)
    at c (handlebars.min.js:27)
    at d (handlebars.min.js:27)
    at e (handlebars.min.js:28)
    at Object.h (handlebars.min.js:27)
    at Object.c [as invokePartial] (handlebars.min.js:27)
    at eval (eval at createFunctionContext (handlebars.min.js:29), <anonymous>:10:31)
    at Object.h [as inverse] (handlebars.min.js:27)
    at Object.<anonymous> (handlebars.min.js:27)
    at Object.c (handlebars.min.js:27)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29), <anonymous>:23:47)
    at c (handlebars.min.js:27)
    at d (handlebars.min.js:27)
    at e (handlebars.min.js:28)
    at renderTemplate (foundry.js:6906)
    at async MonsterBlock5e._renderInner (foundry.js:5230)
    at async MonsterBlock5e._renderInner (foundry.js:5791)
    at async MonsterBlock5e._render (foundry.js:5073)
    at async MonsterBlock5e._render (foundry.js:5780)
logCompatibilityWarning @ commons.js:1696
get @ base-sheet.mjs:116
lookupProperty @ handlebars.min.js:27
eval @ VM7110:16
c @ handlebars.min.js:27
d @ handlebars.min.js:27
e @ handlebars.min.js:28
h @ handlebars.min.js:27
c @ handlebars.min.js:27
eval @ VM7069:21
c @ handlebars.min.js:27
d @ handlebars.min.js:27
e @ handlebars.min.js:28
h @ handlebars.min.js:27
c @ handlebars.min.js:27
eval @ VM7050:10
h @ handlebars.min.js:27
(anonymous) @ handlebars.min.js:27
c @ handlebars.min.js:27
eval @ VM7051:23
c @ handlebars.min.js:27
d @ handlebars.min.js:27
e @ handlebars.min.js:28
renderTemplate @ foundry.js:6906
async function (async)
renderTemplate @ foundry.js:6905
_renderInner @ foundry.js:5230
_renderInner @ foundry.js:5791
_render @ foundry.js:5073
async function (async)
_render @ foundry.js:5067
_render @ foundry.js:5780
render @ foundry.js:5026
render @ foundry.js:6352
_onClickDocumentName @ foundry.js:60169
🎁call_wrapped @ libWrapper-wrapper.js:507
checkClickDocumentName @ monks-active-tiles.js:1774
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁SidebarDirectory.prototype._onClickDocumentName#0 @ libWrapper-wrapper.js:189
🎁call_wrapped @ libWrapper-wrapper.js:507
clickDocumentName @ monks-active-tiles.js:1722
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁ActorDirectory.prototype._onClickDocumentName#0 @ libWrapper-wrapper.js:189
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:747 d {description: undefined, fileName: undefined, lineNumber: undefined, endLineNumber: undefined, message: 'An error occurred while rendering MonsterBlock5e 8…ng helper: "moblok-equals"\n[No packages detected]', …}

2022-10-03 02:02 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> +		data.data.attributes.hp.average = this.constructor.averageRoll(data.data.attributes.hp.formula, data.rollData);
I don't really understand why this line was changed. It doesn't seem to fix anything, but actually makes the average no longer calculate correctly.

2022-10-03 02:06 UTC, merged