Handle continued damage text
zeel01/MonsterBlocks pull request #58
Opened 2021-02-20 21:11 UTC by jeremyregnerus

The following are changes for issue #48 that handle supporting additional text after weapon damage has been displayed. This includes starting the text with a comma or whitespace. This will then forgo the period and instead continue the inline text.

2021-02-22 15:26 UTC, zeel01 requested changes
I'm not sure if I'll have time to get this merged today, there are some changes I would want to make first. But I greatly appreciate the help!

2021-02-22 15:26 UTC, zeel01 commented on actor-sheet.html
> +								text=( localize "MOBLOKS5E.AttackVersatile"
Not sure what's up with the whitespace.

2021-02-22 15:26 UTC, zeel01 commented on actor-sheet.html
> +			{{~#unless (moblok-moretext item.data.description.value) }}{{~localize "MOBLOKS5E.Continue"}}{{/unless~}}
Why is `Continue` different from `FullStop`? We can add the whitespace is Handlebars by adding a space inside the `unless` after it.

2021-02-22 15:26 UTC, zeel01 commented on lang/en.json
> +	"MOBLOKS5E.Continue": ". ",
I'm willing to have this sort of thing if there is a linguistic reason it needs to be this way. Otherwise, I think I would prefer to see the space added programmatically rather than adding a string with it.

2021-02-22 15:26 UTC, zeel01 commented on monsterblock.js
> +			return desc.startsWith('\s', desc.indexOf('>') + 1) || desc.startsWith('&nbsp;', desc.indexOf('>') + 1) || desc.startsWith(',', desc.indexOf('>') + 1);
`desc.startsWith('\s', desc.indexOf('>') + 1)`

Should probably go ahead and add some comments explaining what this actually does.

2021-02-22 15:26 UTC, zeel01 commented on monsterblock.js
> +			return desc.startsWith('\s', desc.indexOf('>') + 1) || desc.startsWith('&nbsp;', desc.indexOf('>') + 1) || desc.startsWith(',', desc.indexOf('>') + 1);
Prefer to make chains of conditions multi-line so that scrolling horizontally isn't required (I know, I'm not always consistent, I need to do better).

2021-02-22 15:26 UTC, zeel01 commented on monsterblock.js
> +		"moblok-moretext": (desc) => { // Checks if description text starts with a space or a comma.
Handlebars helpers are a slippery slope, they *seem* like an easy way to add functionality, unfortunately they really suck for a few reasons - one of which is that they occupy global scope. Everyone's helpers get lumped into one big object which sucks. That's why the `moblok-` to ensure no overlaps.

Since this is a single-use helper (that is, it is only used for one purpose) I think I would rather add a property on the item data to facilitate this instead.

2021-02-22 16:09 UTC, jeremyregnerus commented on actor-sheet.html
> +								text=( localize "MOBLOKS5E.AttackVersatile"
These whitespaces were in the original code, and I scrubbed them trying to figure out where the extra whitespace was being added before / after the comma / period.

2021-02-22 16:10 UTC, jeremyregnerus commented on actor-sheet.html
> +			{{~#unless (moblok-moretext item.data.description.value) }}{{~localize "MOBLOKS5E.Continue"}}{{/unless~}}
I could not find a way to add the whitespace after the period and not put a whitespace before the comma without using this tactic.

2021-02-22 16:10 UTC, jeremyregnerus commented on lang/en.json
> +	"MOBLOKS5E.Continue": ". ",
I could not find a way to add the whitespace after the period and not put a whitespace before the comma without using this tactic.

2021-02-22 16:12 UTC, jeremyregnerus commented on monsterblock.js
> +		"moblok-moretext": (desc) => { // Checks if description text starts with a space or a comma.
I agree with you here completely, and adding a property would be the way I would do this in a c# object to avoid converters. However, when I started looking at the code, I just wasn't sure how to do this in js. That's where the comment I sent you on discord came from that there was some janky code (ie using the handlebar helper and the Continue string). This will take some time for me to really get into understanding the how the class does this.

2021-02-22 17:28 UTC, zeel01 commented on monsterblock.js
> +		"moblok-moretext": (desc) => { // Checks if description text starts with a space or a comma.
I apologize for how big a mess a lot of this is. Many iterations of madness late at night...

2021-03-03 15:08 UTC, jeremyregnerus commented on monsterblock.js
> +		"moblok-moretext": (desc) => { // Checks if description text starts with a space or a comma.
I haven't forgotten about this, I'm just out of town through the end of this weekend. Next week, I should be able to look at these changes.

2021-03-05 14:21 UTC, jeremyregnerus commented on monsterblock.js
> +		"moblok-moretext": (desc) => { // Checks if description text starts with a space or a comma.
I wanted to verify, is this where you would like me to contain the property that would define if the text is continuous?
![image](https://user-images.githubusercontent.com/7407481/110127884-2556a800-7d94-11eb-9dfa-621830fbc21e.png)

2021-03-08 00:35 UTC, zeel01 commented
Implemented this feature via: https://github.com/zeel01/MonsterBlocks/commit/7db2c2f3673ec3a9941cabe5b4f44a6a5e918c6d

2021-03-08 00:35 UTC, closed without merging