Several visual changes for multiple issues
zeel01/MonsterBlocks pull request #66
Opened 2021-03-11 13:25 UTC by jeremyregnerus

This branch includes the following

- Resolves issue #62 by using the activation condition field as a form of alternate target text. 
- Resolves issue #65 to support thrown weapons. This uses the mostly hidden width field, which is used only for line attacks. I have not found a NPC with a conflict.
- Resolves issues #45 by hiding the 'right-click' to edit tooltip on the portrait when not in edit mode
- Shows ranges on weapon attacks with a value of zero as '0', not 'null'
- Added a module and sheet option to disable the zoom on hover of the npc portrait, implemented with flags and a toggle like the rest of the options in monsterblocks

2021-03-11 13:49 UTC, jeremyregnerus commented
There is a second commit that also includes a resolution to issue #44.

2021-03-11 13:55 UTC, jeremyregnerus commented on scripts/dnd5e/MonsterBlock5e.js
> +			range: game.i18n.format(this.isThrownAttack(attack) ? "MOBLOKS5E.ThrownRange" : "MOBLOCKS5E.AttackRange", {
There is a bug here. I thought I could simplify my previous implementation, but it's causing issues trying to pass a single json object to 2 different formats.

2021-03-11 14:37 UTC, jeremyregnerus commented on scripts/dnd5e/MonsterBlock5e.js
> +			range: game.i18n.format(this.isThrownAttack(attack) ? "MOBLOKS5E.ThrownRange" : "MOBLOCKS5E.AttackRange", {
Resolved with following commit https://github.com/zeel01/MonsterBlocks/pull/66/commits/5ae080c4e76abc8f3ec6101483b3f1f548057c04

2021-03-11 21:03 UTC, jeremyregnerus commented
Latest commit resolves
- Issue #49 supporting features with an action cost of none being listed above the actions section
- Issue #61 where Bonus actions are always listed above the actions section in the WotC stat blocks

2021-03-11 21:36 UTC, jeremyregnerus commented
I am trying to implement that last commit the same way you handled spellcasting, and I keep getting an error message that isNotAction and isBonusAction are not functions. Do you have any idea why these wouldn't be working as follows?

```
	static isBonusAction(item) {
		return item.data?.activation?.type === "bonus";
	}

	static isNotAction(item) {
		return item.data?.activation?.type === "none";
	}

	static isAction(item) {
		return item.data?.activation?.type && !this.isNotAction(item) && !this.isBonusAction(item);
	}
```

2021-03-11 22:01 UTC, zeel01 commented
Are you calling any of those methods from other methods that aren't static?

2021-03-11 22:52 UTC, zeel01 requested changes

2021-03-11 22:52 UTC, zeel01 commented on monsterblock.js
> +	game.settings.register("monsterblock", "zoom-profile-image", {
So, it looks like you added a setting for whether or not hovering over the profile image causes it to expand.

I'm not totally sure I'm sold on doing that, but if a new flag is added, there is another place it needs to be added: `get defaultFlags()` needs to define the default state of the flag.

I feel like Monster Blocks already has far too many settings though, so I'm a bit unsure about adding additional ones.

2021-03-11 22:52 UTC, zeel01 commented on templates/dnd5e/parts/header/identity.hbs
> +	<figure class="profile-image {{#if flags.zoom-profile-image}}profile-image-hover{{/if}}">
Also, if the class is toggled higher up, we don't need to duplicate this condition.

2021-03-11 22:52 UTC, zeel01 commented on monsterblock.css
> +.monsterblock.compact-layout .profile-image-hover:hover,
I would probably use a different name for this class, since it's hard to intuit why the class is called `hover` *and* we are styling the `:hover` state. Typically when a class name has "hover" in it, it's because someone is toggling the class in JavaScript to provide hover detection instead of using CSS.

2021-03-11 22:52 UTC, zeel01 commented on templates/dnd5e/bio.hbs
> +		<figure class="profile-image {{#if flags.zoom-profile-image}}profile-image-hover{{/if}}">
For this kind of conditional class, I prefer to instead put the class on a higher level element (such as the main `form` element). This keeps the template clean, but the CSS will still be able to behave appropriately.

2021-03-11 22:52 UTC, zeel01 commented on templates/dnd5e/switches.hbs
> +		<li>
So I added a new "switch" template which I eventually want to convert all switches to use. And later on, I'm going to pull the switch definitions out altogether and just loop through an object the way I do for the menus. So here, I would prefer to use the new switch partial.

(The first two switches are now using the partial, I didn't want to spend the time converting them all yet, but that's the plan)

2021-03-11 22:52 UTC, zeel01 commented on lang/en.json
> +	"MOBLOKS5E.zoom-profile-image-hint": "By defauly zoom the profile image when hovering over it.",
Looks like a typo there, `"defauly"`

2021-03-11 22:52 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> +			target: atkd.activation.condition ? atkd.activation.condition : game.i18n.format("MOBLOKS5E.AttackTarget", {
Should this condition really then skip the rest of this formatting?

2021-03-11 22:52 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> +		return this.isThrownAttack(attack) ? game.i18n.localize("MOBLOKS5E.ThrownLabel") : CONFIG.DND5E.itemActionTypes[attack?.data?.data?.actionType] || "";
Hmm, the `ThrownLabel` takes the same form as the `itemActionTypes` so this makes sense. But it makes this method seem a bit messy.

Maybe just a code formatting issue, I'm not sure how I would break it down further.

2021-03-11 22:52 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> +		return attack?.data?.data?.properties.thr;
I would toss another `?.` in at the end to be safe. I've gotten so tired of weird edge cases where expected properties didn't exist, so I just check them all now...

2021-03-11 22:52 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> +				melee: atkd.target?.width ? atkd.target?.width : 0,
Why is the melee range based on the width? I don't think that's the intended way for the data to be used.

2021-03-11 22:52 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> +		return item.data?.activation?.type && item.data.activation.type != "none" && item.data.activation.type != "bonus";
Are the actions that are none/bonus actually ending up under features? I feel like they would be ending up under "equipment" because that's the catch all.

2021-03-11 22:52 UTC, zeel01 commented on templates/dnd5e/parts/header/attributes/movement.hbs
> +{{#if flags.editing}}<div class="hover-only select-field" data-select-key="data.attributes.movement.units" data-selected-value="{{data.attributes.movement.units}}">
I keep forgetting to fix this.

2021-03-12 02:07 UTC, jeremyregnerus commented on lang/en.json
> +	"MOBLOKS5E.zoom-profile-image-hint": "By defauly zoom the profile image when hovering over it.",
Correct, I've made this change

2021-03-12 02:12 UTC, jeremyregnerus commented on scripts/dnd5e/MonsterBlock5e.js
> +			target: atkd.activation.condition ? atkd.activation.condition : game.i18n.format("MOBLOKS5E.AttackTarget", {
The intention here was noted in issue #62 that some attacks have completely unique descriptors for their targeting. By using the activation.condition property, it will allow a user to specify any unique or edge case targeting parameters without worry of any additional formatting.

2021-03-12 02:15 UTC, jeremyregnerus commented on scripts/dnd5e/MonsterBlock5e.js
> +		return this.isThrownAttack(attack) ? game.i18n.localize("MOBLOKS5E.ThrownLabel") : CONFIG.DND5E.itemActionTypes[attack?.data?.data?.actionType] || "";
Currently, the dnd5e system doesn't have an attack.data.data.actionType of thrown to leverage, which is why I used this method to define the label for thrown attacks.

2021-03-12 02:22 UTC, jeremyregnerus commented on scripts/dnd5e/MonsterBlock5e.js
> +		return item.data?.activation?.type && item.data.activation.type != "none" && item.data.activation.type != "bonus";
Feats do show up correctly under the Features section. I believe this is because you are also evaluating special features by their type (feat).
![image](https://user-images.githubusercontent.com/7407481/110882409-de931180-82af-11eb-974c-2b57382d8f52.png)

2021-03-12 02:23 UTC, jeremyregnerus commented on lang/en.json
> +	"MOBLOKS5E.zoom-profile-image-hint": "By defauly zoom the profile image when hovering over it.",
Resolved in next commit

2021-03-12 02:35 UTC, jeremyregnerus commented on scripts/dnd5e/MonsterBlock5e.js
> +				melee: atkd.target?.width ? atkd.target?.width : 0,
This method was to provide some sort of property to store the value of the melee reach value when combined with a ranged attack to create a thrown weapon profile. Currently the dnd5e system doesn't have support this, and instead would require you to create two separate weapon entries; one for the melee attack, and one for the ranged attack. There are no cases where you would every create a line as a targeting parameter with a thrown weapon, so I decided to use this property in this alternative case. Without some place to store the property, thrown weapons wouldn't work. The reach is not the same for all creatures, either by size or weapon.

2021-03-12 02:36 UTC, jeremyregnerus commented on scripts/dnd5e/MonsterBlock5e.js
> +		return attack?.data?.data?.properties.thr;
Resolved in next commit.

2021-03-12 02:40 UTC, jeremyregnerus commented on monsterblock.js
> +	game.settings.register("monsterblock", "zoom-profile-image", {
I can pull this and just use it in my own fork. I just find the image is always popping up covering things when I'm trying to get to them. There's a lot of comments around this and it may be easier to just remove it from the main branch.

2021-03-12 02:43 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> +				melee: atkd.target?.width ? atkd.target?.width : 0,
Hmm, I would like to avoid this sort of thing.

I think we might have to hold off on the thrown weapon feature, I really don't like misappropriating a filed even if it's not being used.

I think it would be better to file an issue on the system. We could even submit a merge request to the system to separate reach from range.

2021-03-12 02:49 UTC, zeel01 commented on scripts/dnd5e/MonsterBlock5e.js
> +			target: atkd.activation.condition ? atkd.activation.condition : game.i18n.format("MOBLOKS5E.AttackTarget", {
Ah, I see what you're doing. I'll have to think about this one. It's not quite like the width thing, but I'm not sure it the "right" option either.

2021-03-12 02:51 UTC, zeel01 commented on monsterblock.js
> +	game.settings.register("monsterblock", "zoom-profile-image", {
Yeah... You aren't wrong.

2021-03-12 02:57 UTC, jeremyregnerus commented on templates/dnd5e/parts/header/identity.hbs
> +	<figure class="profile-image {{#if flags.zoom-profile-image}}profile-image-hover{{/if}}">
Resolved in next commit.

2021-03-12 02:58 UTC, jeremyregnerus commented on templates/dnd5e/bio.hbs
> +		<figure class="profile-image {{#if flags.zoom-profile-image}}profile-image-hover{{/if}}">
Resolved in next commit.

2021-03-12 02:58 UTC, jeremyregnerus commented on monsterblock.css
> +.monsterblock.compact-layout .profile-image-hover:hover,
Resolved in next commit with .profile-image-zoom

2021-03-12 03:37 UTC, jeremyregnerus commented on templates/dnd5e/switches.hbs
> +		<li>
Resolving this in next commit. Also updating all of the other switch settings.

2021-03-12 03:45 UTC, jeremyregnerus commented
I pushed a bunch of changes. I went through all of the comments to hopefully clarify my intent on both the thrown weapon profiles as well as alternate target text.
I also migrated all of the flag settings to your new partial.

2021-03-12 03:48 UTC, jeremyregnerus commented
> Are you calling any of those methods from other methods that aren't static?
> 
> Sometimes this happens if you don't do a hard refresh too.

I found the only way to resolve this was the call the className.methodName (_this is how this is done in c# as well_), using this.methodName was causing the issue on the static methods. I've seen cases where you've done this, but I also saw this was a reproduceable issue with other existing static methods.

2021-03-12 03:55 UTC, jeremyregnerus commented on scripts/dnd5e/MonsterBlock5e.js
> +				melee: atkd.target?.width ? atkd.target?.width : 0,
> Hmm, I would like to avoid this sort of thing.
> 
> I think we might have to hold off on the thrown weapon feature, I really don't like misappropriating a filed even if it's not being used.
> 
> I think it would be better to file an issue on the system. We could even submit a merge request to the system to separate reach from range.

Fair enough, I can remove this and keep it on my own branch. However, I am extremely doubtful he will do this, he objected to even adding "target" to the list of target types.
https://gitlab.com/foundrynet/dnd5e/-/issues/974

2021-03-12 13:02 UTC, closed without merging